print("Videoaulas Neri sobre Python")
print("Acesse www.informaticon.com.br email=videoaulaneri@gmail.com")
print("------------------------------------------------------------")
nome=input("Dogote sei nome.: ")
idade=input("Digite a idade.: ")
salario=input("Digite o salario.: ")
print("Nome.: ", nome, " - idade", idade, " - salario ", salario)
print("Nome.: %s - idade %s - salario %s " %(nome, idade, salario))