print("Videoaulas Neri sobre Python")
print("Acesse www.informaticon.com.br email=videoaulaneri@gmail.com")
print("------------------------------------------------------------")

nome=input("Digote sei nome.: ")
print("Capitalize (primeiro caracter em maiúsculo) = ", nome.capitalize())
print("Center = centraliza com espaços em branco ",nome.center(30))
print("Quantas letras e tem no nome ", nome.count("e"))
print("Retorna true se o nome terminar em ke: ",nome.endswith("ke"))
print("Find retorna a posição de String ", nome.find("n"))
print("Find retorna a posição de String ", nome.find("n", 0))
print("Find retorna a posição de String ", nome.find("n", 3))
print("Find retorna a posição de String ", nome.find("n", 1))
print("Find retorna a posição de String ", nome.find("n", 2, 6))
print("Find retorna a posição de String ", nome.find("n", 2, 3))
print("Index retorna posicao da primeira ocorrencia ", nome.index("n"))
print("Index retorna posicao da primeira ocorrencia ", nome.index("y", 2))