print("Videoaulas Neri sobre Python")
print("Acesse www.informaticon.com.br email=videoaulaneri@gmail.com")
print("------------------------------------------------------------")

nome=input("Digote sei nome.: ")
print("isalpha = ", nome.isalpha())
print("isdecimal = ", nome.isdecimal())
print("isdigit = ", nome.isdigit())
print("isnumeric = ", nome.isnumeric())
print("islower = ", nome.islower())
print("lower = ", nome.lower())
print("isupper = ", nome.isupper())
print("upper = ", nome.upper())
print("istitle = ", nome.istitle())
print("title = ", nome.title())
print("isspace = ", nome.isspace())